### ISSUE TITLE
Xauthority file path

### ISSUE THREAD

**Issue by HojaeAhn** [sdss/lvmtan#2]
When I run the acter after installing lvmtan, the error occurred.

Error: statfs /home/hojae/.Xauthority: no such file or directory

This error came from the path of Xauthority is different on Ubuntu.
I solved the problem by correcting the path in Line60 of /lvmtan/container/__init__.py.
before)  system_xauthority=PosixPath('~/.Xauthority').expanduser()
after)     system_xauthority=PosixPath('/run/user/1000/gdm/Xauthority').expanduser()

**Comment by wasndas** [comment]
Fixed.
